"""
Lista completa de Pokémon das gerações 1-8 com variações (Mega, Alola, Galar, etc).
"""

# Lista completa de Pokémon com variações
POKEMON_LIST = [
    # Generation 1
    "Bulbasaur", "Ivysaur", "Venusaur", "Venusaur-Mega",
    "Charmander", "Charmeleon", "Charizard", "Charizard-Mega-X", "Charizard-Mega-Y",
    "Squirtle", "Wartortle", "Blastoise", "Blastoise-Mega",
    "Caterpie", "Metapod", "Butterfree",
    "Weedle", "Kakuna", "Beedrill", "Beedrill-Mega",
    "Pidgeot", "Pidgeotto", "Pidgeotto", "Pidgeot-Mega",
    "Rattata", "Rattata-Alola", "Raticate", "Raticate-Alola", "Raticate-Alola-Totem",
    "Spearow", "Fearow",
    "Ekans", "Arbok",
    "Pikachu", "Raichu", "Raichu-Alola",
    "Pichu",
    "Clefairy", "Clefable",
    "Vulpix", "Vulpix-Alola", "Ninetales", "Ninetales-Alola",
    "Jigglypuff", "Wigglytuff",
    "Zubat", "Golbat", "Crobat",
    "Oddish", "Gloom", "Vileplume", "Bellossom",
    "Paras", "Parasect",
    "Venonat", "Venomoth",
    "Diglett", "Diglett-Alola", "Dugtrio", "Dugtrio-Alola",
    "Meowth", "Meowth-Alola", "Meowth-Galar", "Persian", "Persian-Alola",
    "Psyduck", "Golduck",
    "Mankey", "Primeape",
    "Growlithe", "Growlithe-Hisui", "Arcanine", "Arcanine-Hisui",
    "Poliwag", "Poliwhirl", "Poliwrath",
    "Abra", "Kadabra", "Alakazam", "Alakazam-Mega",
    "Machop", "Machoke", "Machamp",
    "Bellsprout", "Weepinbell", "Victreebel",
    "Tentacool", "Tentacruel",
    "Slowpoke", "Slowpoke-Galar", "Slowbro", "Slowbro-Mega", "Slowbro-Galar", "Slowking", "Slowking-Galar",
    "Seel", "Dewgong",
    "Shellder", "Cloyster",
    "Gastly", "Haunter", "Gengar", "Gengar-Mega",
    "Onix", "Steelix", "Steelix-Mega",
    "Drowzee", "Hypno",
    "Krabby", "Kingler",
    "Voltorb", "Voltorb-Hisui", "Electrode", "Electrode-Hisui",
    "Exeggcute", "Exeggcute-Alola", "Exeggutor", "Exeggutor-Alola",
    "Cubone", "Cubone-Alola", "Marowak", "Marowak-Alola", "Marowak-Alola-Totem",
    "Hitmonlee", "Hitmonchan", "Hitmontop",
    "Lickitung", "Lickilicky",
    "Rhyhorn", "Rhydon", "Rhyperior",
    "Chansey", "Blissey",
    "Tangela", "Tangrowth",
    "Kangaskhan", "Kangaskhan-Mega",
    "Horsea", "Seadra", "Kingdra",
    "Goldeen", "Seaking",
    "Staryu", "Starmie",
    "Mr-Mime", "Mr-Mime-Galar", "Mime-Jr", "Mr-Rime",
    "Scyther", "Scizor", "Scizor-Mega",
    "Jynx", "Smoochum",
    "Electabuzz", "Electivire",
    "Magby", "Magnemite", "Magneton", "Magnezone",
    "Farfetchd", "Farfetchd-Galar", "Sirfetchd",
    "Doduo", "Dodrio",
    "Seel", "Dewgong",
    "Grimer", "Grimer-Alola", "Muk", "Muk-Alola",
    "Shellder", "Cloyster",
    "Gastly", "Haunter", "Gengar", "Gengar-Mega",
    "Onix", "Steelix", "Steelix-Mega",
    "Drowzee", "Hypno",
    "Krabby", "Kingler",
    "Exeggcute", "Exeggutor",
    "Marowak",
    "Weezing", "Weezing-Galar",
    "Rhyhorn", "Rhydon",
    "Chansey",
    "Kangaskhan", "Kangaskhan-Mega",
    "Horsea", "Seadra",
    "Goldeen", "Seaking",
    "Staryu", "Starmie",
    "Magikarp", "Gyarados", "Gyarados-Mega",
    "Lapras", "Lapras-Gmax",
    "Ditto",
    "Eevee", "Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon", "Leafeon", "Glaceon", "Sylveon",
    "Porygon", "Porygon2", "Porygon-Z",
    "Snorlax", "Munchlax",
    "Articuno", "Zapdos", "Moltres",
    "Dratini", "Dragonair", "Dragonite", "Dragonite-Mega",
    "Mewtwo", "Mewtwo-Mega-X", "Mewtwo-Mega-Y",
    "Mew",

    # Generation 2
    "Chikorita", "Bayleef", "Meganium",
    "Cyndaquil", "Quilava", "Typhlosion", "Typhlosion-Hisui",
    "Totodile", "Croconaw", "Feraligatr",
    "Sentret", "Furret",
    "Hoothoot", "Noctowl",
    "Ledyba", "Ledyba-Hisui", "Ledian",
    "Spinarak", "Girafarig", "Farigiraf",
    "Crobat",
    "Chinchou", "Lanturn",
    "Pichu",
    "Cleffa", "Clefairy",
    "Igglybuff", "Jigglypuff",
    "Togepi", "Togetic", "Togekiss",
    "Tyrogue", "Hitmonlee", "Hitmonchan",
    "Smoochum", "Jynx",
    "Elekid", "Electabuzz",
    "Magby", "Magnemite",
    "Azurill", "Marill", "Azumarill",
    "Sudowoodo",
    "Politoed", "Poliwrath",
    "Hoppip", "Skiploom", "Jumpluff",
    "Aipom", "Ambipom",
    "Sunkern", "Sunflora",
    "Yanma", "Yanmega",
    "Wooper", "Wooper-Paldea", "Clodsire", "Clodsire-Paldea",
    "Quagsire",
    "Espeon", "Umbreon",
    "Murkrow", "Honchkrow",
    "Slowking", "Slowking-Galar",
    "Misdreavus", "Mismagius",
    "Unown",
    "Wobbuffet", "Wynaut",
    "Girafarig", "Farigiraf",
    "Pineco", "Forretress",
    "Dunsparce", "Dudunsparce",
    "Girafarig", "Farigiraf",
    "Teddiursa", "Ursaring", "Ursaluna", "Ursaluna-Bloodmoon",
    "Slugma", "Magcargo",
    "Swinub", "Piloswine", "Mamoswine",
    "Corsola", "Cursola", "Cursola-Galar",
    "Remoraid", "Octillery",
    "Mantine", "Mantyke",
    "Skarmory",
    "Houndour", "Houndoom", "Houndoom-Mega",
    "Phanpy", "Donphan",
    "Porygon2", "Porygon-Z",
    "Tyrogue", "Hitmonlee", "Hitmonchan",
    "Smoochum", "Jynx",
    "Elekid", "Electabuzz",
    "Magby", "Magnemite",
    "Raikou", "Entei", "Suicune",
    "Larvitar", "Pupitar", "Tyranitar", "Tyranitar-Mega",
    "Lugia",
    "Ho-Oh",
    "Celebi",

    # Generation 3
    "Treecko", "Grovyle", "Sceptile", "Sceptile-Mega",
    "Torchic", "Combusken", "Blaziken", "Blaziken-Mega",
    "Mudkip", "Marshtomp", "Swampert", "Swampert-Mega",
    "Poochyena", "Mightyena",
    "Zigzagoon", "Zigzagoon-Galar", "Linoone", "Linoone-Galar", "Obstagoon",
    "Wurmple", "Silcoon", "Beautifly", "Cascoon", "Dustox",
    "Lotad", "Lombre", "Ludicolo",
    "Seedot", "Nuzleaf", "Shiftry",
    "Taillow", "Swellow",
    "Wingull", "Pelipper",
    "Ralts", "Kirlia", "Gardevoir", "Gardevoir-Mega", "Gallade", "Gallade-Mega",
    "Surskit", "Masquerain",
    "Shroomish", "Breloom",
    "Slakoth", "Vigoroth", "Slaking",
    "Wingull", "Pelipper",
    "Barboach", "Whiscash",
    "Corphish", "Crawdaunt",
    "Feebas", "Milotic",
    "Carvanha", "Sharpedo", "Sharpedo-Mega",
    "Wailmer", "Wailord",
    "Numel", "Camerupt", "Camerupt-Mega",
    "Torkoal", "Torkoal-Gmax",
    "Spoink", "Grumpig",
    "Spinda",
    "Trapinch", "Vibrava", "Flygon",
    "Cacnea", "Cacturne",
    "Swablu", "Altaria", "Altaria-Mega",
    "Zangoose", "Seviper",
    "Lunatone", "Solrock",
    "Barboach", "Whiscash",
    "Corphish", "Crawdaunt",
    "Baltoy", "Claydol",
    "Kecleon",
    "Shuppet", "Banette", "Banette-Mega",
    "Duskull", "Dusclops", "Dusknoir",
    "Tropius",
    "Chimecho", "Chingling", "Chimera",
    "Absol", "Absol-Mega",
    "Wynaut", "Wobbuffet",
    "Snorunt", "Glalie", "Glalie-Mega", "Froslass",
    "Spheal", "Sealeo", "Walrein",
    "Clamperl", "Huntail", "Gorebyss",
    "Relicanth",
    "Luvdisc",
    "Bagon", "Shelgon", "Salamence", "Salamence-Mega",
    "Beldum", "Metang", "Metagross", "Metagross-Mega",
    "Regirock", "Regice", "Registeel", "Regieleki", "Regidrago",
    "Latias", "Latias-Mega", "Latios", "Latios-Mega",
    "Kyogre", "Kyogre-Primal",
    "Groudon", "Groudon-Primal",
    "Rayquaza", "Rayquaza-Mega",
    "Jirachi",
    "Deoxys", "Deoxys-Attack", "Deoxys-Defense", "Deoxys-Speed",

    # Generation 4
    "Turtwig", "Grotle", "Torterra",
    "Chimchar", "Monferno", "Infernape",
    "Piplup", "Prinplup", "Empoleon",
    "Starly", "Staravia", "Staraptor",
    "Bidoof", "Bibarel",
    "Buizel", "Floatzel",
    "Cherubi", "Cherrim", "Cherrim-Sunshine",
    "Shellos", "Gastrodon",
    "Ambipom", "Aipom",
    "Drifloon", "Drifblim",
    "Buneary", "Lopunny", "Lopunny-Mega",
    "Glameow", "Purugly",
    "Chatot",
    "Spiritomb",
    "Gible", "Gabite", "Garchomp", "Garchomp-Mega",
    "Munchlax", "Snorlax",
    "Riolu", "Lucario", "Lucario-Mega",
    "Happiny", "Chansey",
    "Chatot",
    "Carnivine",
    "Rokon", "Arcanine",
    "Rampardos",
    "Cradily",
    "Armaldo",
    "Feebas", "Milotic",
    "Carvanha", "Sharpedo", "Sharpedo-Mega",
    "Wailmer", "Wailord",
    "Barboach", "Whiscash",
    "Corphish", "Crawdaunt",
    "Feebas", "Milotic",
    "Carvanha", "Sharpedo",
    "Wailmer", "Wailord",
    "Mantyke", "Mantine",
    "Snover", "Abomasnow", "Abomasnow-Mega",
    "Weavile",
    "Magnezone",
    "Rhyperior",
    "Tangrowth",
    "Electivire",
    "Magmortar",
    "Togekiss",
    "Yanmega",
    "Leafeon", "Glaceon",
    "Gliscor",
    "Mamoswine",
    "Porygon-Z",
    "Gallade",
    "Probopass",
    "Dusknoir",
    "Froslass",
    "Rotom", "Rotom-Heat", "Rotom-Wash", "Rotom-Frost", "Rotom-Fan", "Rotom-Mow",
    "Uxie", "Mesprit", "Azelf",
    "Dialga", "Palkia",
    "Heatran",
    "Regigigas",
    "Giratina", "Giratina-Origin",
    "Cresselia",
    "Phione", "Manaphy",
    "Darkrai",
    "Shaymin", "Shaymin-Sky",
    "Arceus",

    # Generation 5
    "Snivy", "Servine", "Serperior",
    "Tepig", "Pignite", "Emboar",
    "Oshawott", "Dewott", "Samurott", "Samurott-Hisui",
    "Patrat", "Watchog",
    "Lillipup", "Herdier", "Stoutland", "Stoutland-Galar",
    "Pidove", "Tranquill", "Unfezant",
    "Blitzle", "Zebstrika",
    "Roggenrola", "Boldore", "Gigalith",
    "Woobat", "Swoobat",
    "Drilbur", "Excadrill",
    "Audino", "Audino-Mega",
    "Timburr", "Gurdurr", "Conkeldurr",
    "Tympole", "Palpitoad", "Seismitoad",
    "Throh", "Sawk",
    "Sewaddle", "Swadloon", "Leavanny",
    "Venipede", "Whirlipede", "Scolipede",
    "Cottonee", "Whimsicott",
    "Petilil", "Lilligant", "Lilligant-Hisui",
    "Basculin", "Basculin-White-Striped", "Basculegion",
    "Sandile", "Krokonaw", "Krookodile",
    "Darumaka", "Darumaka-Galar", "Darmanitan", "Darmanitan-Galar", "Darmanitan-Galar-Zen",
    "Dwebble", "Crustle",
    "Scraggy", "Scrafty",
    "Sigilyph",
    "Yamask", "Yamask-Unova", "Cofagrigus",
    "Tirtouga", "Carracosta",
    "Archen", "Archeops",
    "Trubbish", "Garbodor",
    "Zorua", "Zorua-Hisui", "Zoroark", "Zoroark-Hisui",
    "Minccino", "Cinccino",
    "Druddigon",
    "Golett", "Golurk",
    "Pawniard", "Pawniard-Hisui", "Bisharp", "Bisharp-Hisui", "Kingambit",
    "Rufflet", "Braviary", "Braviary-Hisui",
    "Vullaby", "Mandibuzz",
    "Heatmor", "Durant",
    "Deino", "Zweilous", "Hydreigon",
    "Larvesta", "Volcarona",
    "Cobalion", "Terrakion", "Virizion", "Calyrex", "Calyrex-Ice", "Calyrex-Shadow",
    "Tornadus", "Tornadus-Therian", "Therian",
    "Thundurus", "Thundurus-Therian",
    "Reshiram", "Zekrom",
    "Landorus", "Landorus-Therian",
    "Kyurem", "Kyurem-Black", "Kyurem-White",
    "Meowth-Galar",

    # Generation 6
    "Chespin", "Quilladin", "Chesnaught",
    "Fennekin", "Braixen", "Delphox",
    "Froakie", "Frogadier", "Greninja", "Greninja-Ash", "Greninja-Gmax",
    "Bunnelby", "Diggersby",
    "Fletchling", "Fletchinder", "Talonflame",
    "Scatterbug", "Spewpa", "Vivillon", "Vivillon-Fancy", "Vivillon-Poké-Ball",
    "Litleo", "Pyroar",
    "Flabébé", "Floette", "Florges",
    "Skiddo", "Gogoat",
    "Pancham", "Pangoro",
    "Furfrou", "Furfrou-Heart", "Furfrou-Star", "Furfrou-Diamond", "Furfrou-Debutante", "Furfrou-Matron", "Furfrou-Dandy", "Furfrou-La-Reine", "Furfrou-Kabuki", "Furfrou-Pharaoh",
    "Espurr", "Meowstic", "Meowstic-F",
    "Honedge", "Doublade", "Aegislash", "Aegislash-Blade",
    "Spritzee", "Aromatisse",
    "Swirlix", "Slurpuff",
    "Inkay", "Malamar",
    "Helioptile", "Heliolisk",
    "Tyrunt", "Tyrantrum",
    "Amaura", "Aurorus",
    "Sylveon",
    "Binacle", "Barbaracle",
    "Skrelp", "Dragalge",
    "Clauncher", "Clawitzer",
    "Rocktomb", "Boldore", "Gigalith",
    "Carbink", "Sligoo", "Goodra",
    "Klefki",
    "Phantump", "Trevenant",
    "Pumpkaboo", "Pumpkaboo-Small", "Pumpkaboo-Large", "Pumpkaboo-Super", "Gourgeist", "Gourgeist-Small", "Gourgeist-Large", "Gourgeist-Super",
    "Bergmite", "Avalugg", "Avalugg-Hisui",
    "Noibat", "Noivern",
    "Xerneas", "Yveltal", "Zygarde", "Zygarde-10", "Zygarde-Complete",
    "Diancie", "Diancie-Mega",
    "Hoopa", "Hoopa-Unbound",
    "Volcanion",

    # Generation 7
    "Rowlet", "Dartrix", "Decidueye", "Decidueye-Hisui",
    "Litten", "Torracat", "Incineroar",
    "Popplio", "Brionne", "Primarina",
    "Pikipek", "Trumbeak", "Toucannon",
    "Yungoos", "Gumshoos",
    "Grubbin", "Charjabug", "Vikavolt",
    "Crabrawler", "Crabominable",
    "Oricorio", "Oricorio-Pom-Pom", "Oricorio-Pau", "Oricorio-Sensu",
    "Cutiefly", "Ribombee",
    "Rockruff", "Rockruff-Dusk", "Lycanroc", "Lycanroc-Midday", "Lycanroc-Midnight", "Lycanroc-Dusk",
    "Wishiwashi", "Wishiwashi-School",
    "Mareanie", "Toxapex",
    "Mudbray", "Mudsdale",
    "Dewpider", "Araquanid",
    "Fomantis", "Lurantis",
    "Morelull", "Shiinotic",
    "Salandit", "Salazzle",
    "Stufful", "Bewear",
    "Bounsweet", "Steenee", "Tsareena",
    "Wimpod", "Golisopod",
    "Sandygast", "Palossand",
    "Pyukumuku",
    "Type-Null", "Silvally", "Silvally-Fire", "Silvally-Water", "Silvally-Electric", "Silvally-Grass", "Silvally-Ice", "Silvally-Fighting", "Silvally-Poison", "Silvally-Ground", "Silvally-Flying", "Silvally-Psychic", "Silvally-Bug", "Silvally-Rock", "Silvally-Ghost", "Silvally-Dragon", "Silvally-Dark", "Silvally-Steel", "Silvally-Fairy",
    "Minior", "Minior-Meteor",
    "Komala",
    "Turtonator",
    "Togedemaru",
    "Mimikyu", "Mimikyu-Busted",
    "Bruxish",
    "Dramidino", "Drakloak", "Dragapult",
    "Jangmo-o", "Hakamo-o", "Kommo-o",
    "Tapu-Koko", "Tapu-Lele", "Tapu-Bulu", "Tapu-Fini",
    "Cosmog", "Cosmoem", "Solgaleo", "Lunala",
    "Nihilego", "Buzzwole", "Pheromosa", "Xurkitree", "Celesteela", "Kartana", "Guzzlord",
    "Necrozma", "Necrozma-Dusk-Mane", "Necrozma-Dawn-Wings", "Necrozma-Ultra",
    "Magearna",
    "Marshadow",
    "Poipole", "Naganadel",
    "Stakataka",
    "Blacephalon",
    "Zeraora",
    "Meltan", "Melmetal", "Melmetal-Gmax",

    # Generation 8
    "Grookey", "Thwackey", "Rillaboom", "Rillaboom-Gmax",
    "Scorbunny", "Raboot", "Cinderace", "Cinderace-Gmax",
    "Sobble", "Drizzile", "Inteleon", "Inteleon-Gmax",
    "Skwovet", "Greedent",
    "Rookidee", "Corvisquire", "Corviknight", "Corviknight-Gmax",
    "Blipbug", "Dottler", "Orbeetle", "Orbeetle-Gmax",
    "Nickit", "Thievul",
    "Wooloo", "Dubwool",
    "Chewtle", "Drednaw", "Drednaw-Gmax",
    "Arrokuda", "Barraskewda",
    "Toxel", "Toxtricity", "Toxtricity-Amped", "Toxtricity-Low-Key", "Toxtricity-Gmax",
    "Sizzlipede", "Centiskorch", "Centiskorch-Gmax",
    "Clobbopus", "Grapploct",
    "Sinistea", "Polteageist",
    "Hatenna", "Hattrem", "Hatterene", "Hatterene-Gmax",
    "Impidimp", "Morgrem", "Grimmsnarl", "Grimmsnarl-Gmax",
    "Milcery", "Alcremie", "Alcremie-Gmax",
    "Falinks",
    "Prookidee", "Corvisquire", "Corviknight",
    "Silicobra", "Sandaconda", "Sandaconda-Gmax",
    "Cramorant", "Cramorant-Gulping", "Cramorant-Gorging",
    "Arrokuda", "Barraskewda",
    "Cursola",
    "Cursola-Galar",
    "Applin", "Flapple", "Flapple-Gmax", "Appletun", "Appletun-Gmax",
    "Silicobra", "Sandaconda",
    "Cramorant",
    "Arrokuda", "Barraskewda",
    "Pikachu-Gmax",
    "Meowth-Galar",
    "Corviknight-Gmax",
    "Orbeetle-Gmax",
    "Drednaw-Gmax",
    "Coalossal-Gmax",
    "Flapple-Gmax",
    "Appletun-Gmax",
    "Sandaconda-Gmax",
    "Cramorant",
    "Arrokuda", "Barraskewda",
    "Toxtricity-Gmax",
    "Centiskorch-Gmax",
    "Hatterene-Gmax",
    "Grimmsnarl-Gmax",
    "Alcremie-Gmax",
    "Machamp-Gmax",
    "Gengar-Gmax",
    "Kingler-Gmax",
    "Lapras-Gmax",
    "Snorlax-Gmax",
    "Charizard-Gmax",
    "Butterfree-Gmax",
    "Venusaur-Gmax",
    "Blastoise-Gmax",
    "Venomoth",
    "Dragonite",
    "Wailord",
    "Gyarados",
    "Alcremie",
    "Eternatus", "Eternatus-Eternamax",
    "Kubfu", "Urshifu", "Urshifu-Rapid-Strike",
    "Zarude", "Zarude-Dada",
    "Calyrex", "Calyrex-Ice", "Calyrex-Shadow",
    "Glastrier", "Spectrier",
]

# Dicionário para busca rápida
POKEMON_DICT = {name.lower(): name for name in POKEMON_LIST}


def get_pokemon_list() -> list:
    """Retorna a lista de Pokémon base (sem variantes Mega, Alola, Galar, etc)."""
    return get_base_pokemon_only()


def search_pokemon(query: str) -> list:
    """
    Busca Pokémon por nome parcial (case-insensitive).
    Retorna apenas pokémon base (sem variantes Mega, Alola, Galar).
    
    Args:
        query: Parte do nome do Pokémon
        
    Returns:
        Lista de Pokémon base que correspondem à busca
    """
    query_lower = query.lower()
    base_pokemon = get_base_pokemon_only()
    return [name for name in base_pokemon if query_lower in name.lower()]


def is_valid_pokemon(name: str) -> bool:
    """Verifica se um nome é um Pokémon válido."""
    return name.lower() in POKEMON_DICT


def get_pokemon_exact_name(name: str) -> str:
    """Retorna o nome correto do Pokémon com capitalização apropriada."""
    return POKEMON_DICT.get(name.lower(), name)


def get_base_pokemon_only() -> list:
    """Retorna lista de Pokémon base (sem variantes Mega, Alola, Galar, etc)."""
    base_pokemon = []
    seen = set()
    
    for pokemon in POKEMON_LIST:
        # Remover sufixos de variantes
        base_name = pokemon.split("-")[0]  # Pega tudo antes do primeiro hífen
        
        # Apenas adicionar se não for duplicado
        if base_name not in seen:
            base_pokemon.append(base_name)
            seen.add(base_name)
    
    return sorted(base_pokemon)
